all: altbit gobackn

altbit:
	gcc -g project2.c altbit-student2.c -o altbit

gobackn:
	gcc -g project2.c gobackn-student2.c -o gobackn

clear_old_files:
	rm -f *.?~
	rm -f \#*#
	rm -f makefile~

clean:
	rm -f *.o
	rm -f a.out
	rm -f altbit
	rm -f gobackn
