require "proj3"
printTable(market)
printTable(TransactionLog)
BuyOrder({security = "Universal", bid = 120.32, amt = 50, buyer = "Ms H"})
BuyOrder({security = "Universal", bid = 134.57, amt = 150, buyer = "Ms G"})
BuyOrder({security = "Universal", bid = 863.57, amt = 38, buyer = "Ms L"})
printTable(market)
printTable(TransactionLog)
SellOrder({security = "Universal", quote = 1289.23, amt = 234, seller = "Mr T"})
SellOrder({security = "Universal", quote = 11.11, amt = 111, seller = "Mr A"})
SellOrder({security = "Universal", quote = 981, amt = 67, seller = "Mr B"})
SellOrder({security = "Universal", quote = 11981, amt = 7, seller = "Mr W"})
printTable(market)
printTable(TransactionLog)
SellOrder({security = "WPI", quote = 181, amt = 15, seller = "Mr Y"})
BuyOrder({security = "WPI", bid = 83.57, amt = 8, buyer = "Mr L"})
SellOrder({security = "WPI", quote = 11, amt = 15, seller = "Mr R"})
BuyOrder({security = "WPI", bid = 8.79, amt = 80, buyer = "Mr K"})
SellOrder({security = "WPI", quote = 1, amt = 150, seller = "Mr U"})
BuyOrder({security = "WPI", bid = 1.57, amt = 18, buyer = "Mr W"})
printTable(market)
printTable(TransactionLog)
BuyOrder({security = "WPI", bid = 80.87, amt = 18, buyer = "Mr C"})
SellOrder({security = "WPI", quote = 190, amt = 45, seller = "Mr V"})
SellOrder({security = "Facebook", quote = 231, amt = 95, seller = "Mr B"})
BuyOrder({security = "Facebook", bid = 85.57, amt = 83, buyer = "Mr N"})
SellOrder({security = "Facebook", quote = 21, amt = 12, seller = "Mr D"})
BuyOrder({security = "Facebook", bid = 857, amt = 9, buyer = "Mr E"})
SellOrder({security = "Facebook", quote = 23, amt = 4, seller = "Mr F"})
BuyOrder({security = "Facebook", bid = 85.5, amt = 3, buyer = "Mr G"})
SellOrder({security = "Facebook", quote = 51, amt = 5, seller = "Mr H"})
BuyOrder({security = "Facebook", bid = 87, amt = 8, buyer = "Mr I"})
